[package]
name = "storage-node"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = "50.0.0"
anyhow = "1"
bytes = "1"
hyper = "1.1.0"
tokio = { version = "1", features = [
    "rt",
    "rt-multi-thread",
    "macros",
] }
datafusion = "35"
